//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControl {
    
    
    public partial class FacilitySummary {
        
        /// <summary>
        /// FacilityDetails1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AppControl.FacilityDetails FacilityDetails1;
        
        /// <summary>
        /// SliderDivDates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivDates;
        
        /// <summary>
        /// PanelDatesContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelDatesContent;
        
        /// <summary>
        /// SliderDivAS400Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivAS400Comments;
        
        /// <summary>
        /// PanelAS400CommentsContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelAS400CommentsContent;
        
        /// <summary>
        /// SliderDivFacilityTypeOf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivFacilityTypeOf;
        
        /// <summary>
        /// PanelFacilityTypeOfContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelFacilityTypeOfContent;
        
        /// <summary>
        /// SliderDivOperatingHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivOperatingHours;
        
        /// <summary>
        /// PanelOperatingHoursContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelOperatingHoursContent;
        
        /// <summary>
        /// SliderDivSubstation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivSubstation;
        
        /// <summary>
        /// PanelSubstationContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelSubstationContent;
        
        /// <summary>
        /// SliderDivVehicle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivVehicle;
        
        /// <summary>
        /// PanelVehicleContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelVehicleContent;
        
        /// <summary>
        /// SliderDivSpecialtyUnits control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivSpecialtyUnits;
        
        /// <summary>
        /// PanelSpecialtyUnits control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelSpecialtyUnits;
        
        /// <summary>
        /// SliderDivOffSiteCampuses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivOffSiteCampuses;
        
        /// <summary>
        /// PanelOffSiteCampuses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelOffSiteCampuses;
        
        /// <summary>
        /// SliderDivServices control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivServices;
        
        /// <summary>
        /// PanelServices control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelServices;
        
        /// <summary>
        /// SliderDivGenericCapSumm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivGenericCapSumm;
        
        /// <summary>
        /// PanelGenericCapSumm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelGenericCapSumm;
        
        /// <summary>
        /// SliderDivOwnership control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivOwnership;
        
        /// <summary>
        /// PanelOwnership control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelOwnership;
        
        /// <summary>
        /// SliderDivKeyPersonnel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivKeyPersonnel;
        
        /// <summary>
        /// PanelKeyPersonnel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelKeyPersonnel;
        
        /// <summary>
        /// SliderDivOperatingInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivOperatingInfo;
        
        /// <summary>
        /// PanelOperatingInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelOperatingInfo;
        
        /// <summary>
        /// SliderDivDrivers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivDrivers;
        
        /// <summary>
        /// PanelDrivers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelDrivers;
        
        /// <summary>
        /// SliderDivInsurance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderDivInsurance;
        
        /// <summary>
        /// PanelInsurance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelInsurance;
        
        /// <summary>
        /// SliderParishesSubstations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderParishesSubstations;
        
        /// <summary>
        /// PanelParishesSubstations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelParishesSubstations;
        
        /// <summary>
        /// SliderVehicles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AtgWebUI.SliderDiv SliderVehicles;
        
        /// <summary>
        /// PanelVehicles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelVehicles;
    }
}
